title: MUSCLE
author: Muscle
theme: mitsushima

menus: 
  HOME: /
  DIRECTORY: /directory
  PAGE: /20
  COMMENT: /comment
  # ABOUT: /about
  #POST:/20

#主页上的README
indexBlog:
  title: "README"

# mermaid chart
mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: true  # default true
  version: "7.1.2" # default v7.1.2
  options:  # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
    #startOnload: true  // default true